version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: mygympartner-db
    environment:
      POSTGRES_DB: mygympartner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mygympartner-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mygympartner-backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/mygympartner
      JWT_SECRET: mygympartner-super-secret-jwt-key-2024
      JWT_EXPIRES_IN: 7d
      PORT: 3001
      NODE_ENV: development
      CORS_ORIGIN: http://localhost:5173
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mygympartner-network
    command: npm run dev

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mygympartner-frontend
    environment:
      VITE_API_URL: http://localhost:3001/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mygympartner-network
    command: npm run dev

volumes:
  postgres_data:

networks:
  mygympartner-network:
    driver: bridge
