[build]
builder = "nixpacks"
buildCommand = "chmod +x railway-build.sh && ./railway-build.sh"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PRISMA_SCHEMA_PATH = "prisma/schema.prisma"
